---
title: "Etude de l'expression de gènes dans certaines zones du cerveau. Visualisation et comparaison de l'expression de ces gènes"
author: "Vincent Guillemot"
date: "Mercredi 24 septembre  2014"
output: pdf_document
---

> Les données *haut-débit*, et en particulier les mesures d'expression de gènes, sont une source inépuisable d'inspiration pour les statisticiens. De nombreuses méthodes ont été ainsi dépoussiérées et adaptés au fait que l'analyse de milliers de variables pose des problèmes tout à fait différents de ce que peut être l'analyse d'une ou deux variables. Par exemple, des méthodes de visualisation comme l'*Analyse en Composantes Principales* ou les *heatmaps*, qui jusqu'à présent peinaient à prendre leur place dans la boîte à outil du statisticien, deviennent maintenant des étapes presque incoutournable de l'analyse.

Le jeu de données qui va nous servir d'exemple est extrait d'une base de données publiques et a donné lieu à la publication suivante

> [ Altered neuronal gene expression in brain regions differentially affected by Alzheimer's disease: a reference data set.
Liang, Winnie S;  Dunckley, Travis;  Beach, Thomas G;  Grover, Andrew;  Mastroeni, Diego et al. (2008)
Physiological genomics  vol. 33 (2) p. 240-56](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2826117/#SD1).

Le jeu de données lui-même est disponible sur [GEO](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE5281).
 
1. Parcourez rapidement l'article pour vous familiariser avec le jeu de données. Sur la page GEO, téléchargez le fichier `GSE5281_sample_characteristics.xls` et ouvrez le à l'aide d'un tableur.

Les données sont disponibles sont la forme d'un fichier compressé `RData` qui contient les niveaux de sondes qui sont différentiellement exprimées à la fois entre plusieurs couples de situations différentes :

```{r}
sondes <- c("1566887_x_at", "233313_at", "241762_at", "239629_at", "237768_x_at",
            "202279_at", "202712_s_at", "205514_at", "202433_at", "201199_s_at",
            "242829_x_at", "215978_x_at", "211071_s_at", "201341_at", "242372_s_at",
            "223480_s_at", "218302_at", "201570_at", "228546_at", "238558_at",
            "219389_at", "235850_at", "226627_at", "209001_s_at", "200027_at",
            "226086_at", "201628_s_at", "230656_s_at", "200639_s_at")
```

L'obtention de ces sondes est décrite dans la table supplémentaire numéro 1 (de l'article ci-dessus).

> Avant toute nouvelle analyse, il vaut mieux effacer la mémoire de travail. Cela se fait grâce à la commande `rm(list=ls())`. C'est particulièrement important lorsque l'on veut relancer une analyse *après corrections d'erreurs de programmation*. Mettez cette commande en haut de votre script.

2. Chargez en mémoire le jeu de données qui se trouve dans le fichier `expression.RData`. *Indice : `load`*. Comment s'appelle le jeu de données que nous venons de charger ? *Indice : `ls`*. Quelle est sa classe ? *Indice : `classe`*. Affichez un résumé de chacune des colonnes de ce tableau de données. *Indice : `str`*. Quelles sont ses dimensions ? *Indice : `dim`*. Quelles sont les noms des lignes et des colonnes ? *Indice : `rownames`, `colnames`*.

Un premier outil de visualisation pour des données haut-débit est le diagramme de Tukey (`boxplot`).

3. Utilisez un `boxplot` pour observer les expressions de quelques-unes (par exemple une dizaine) des puces (les colonnes) du jeu de données. Faites la même chose sur les lignes (les gènes). 

Une représentation très synthétique d'un jeu de données, et qui permet d'identifier d'un coup d’œil différentes sources de variabilités, est l'ACP (Analyse en Composantes Principales). Le principe est de résumer par quelques composantes toutes les variables d'un jeu de données. Ces composantes captures l'une après l'autre les sources les plus importantes de variabilité.

4. Utilisez la commande suivante pour calculer l'ACP du jeu de données : `acp <- prcomp(t(expressions), scale=TRUE)`. Puis `plot(acp)` : cela permet de classer les composantes depuis celle qui capture le plus de variabilité jusqu'à celle qui en capture le moins. Cela permet de savoir quel est la répartition de la variabilité au sein des différentes composantes. Enfin, on peut représenter par des couleurs différents facteurs pour essayer de savoir s'ils corrèlent avec une ou plusieurs composantes. Exécutez la commandes `plot(acp$x, col=as.numeric(y))`. Que venons-nous de faire ? L'ACP est une source importante d'information quand on analyse des données si difficiles à manipuler : c'est un outil qui permet de repérer des sources de biais, des outliers, et de vérifier visuellement qu'un effet est présent dans un jeu de données.

Une autre représentation importante pour l'analyse de données comprenant de nombreuses variables et de nombreux individus est la *Heatmap* : elle est souvent couplée avec des méthodes de *clustering* permettant de créer de façon non-supervisée des groupes de variable et/ou d'individus. Après clustering, on voit ainsi très vite les gènes qui sont sur-exprimés ou sous-exprimés sous différentes conditions.

5. Utilisez la fonction `heatmap` sur le jeu de données `expressions` après avoir transformé celui-ci en matrice (fonction `as.matrix`). Pour changer l'échelle de couleur, utiliser la fonction `terrain.colors` de la librairie `grDevices`. Parcourez l'aide très fournie de cette fonction pour représenter le facteur `y` sur cette figure. Cela requerra l'utilisation de l'argument `RowSideColors` et de l'argument `margins`.

Enfin, après visualisation, il est classique de faire des t-tests et des ANOVAs pour chaque gène : une ANOVA (commande `aov`) permettra de savoir si au moins une des régions définies par le facteur `regions` est en moyenne exprimée différemment des autres, tandis que le t-test (`t.test`) sera utilisé pour savoir par exemple si les témoins présentent une expression différentielle pour le gène considéré par rapport au cas.

6. Sans utiliser de boucle, faites un t-test (`t.test`) et une ANOVA (`aov`) sur une sélection de quelques gènes (2 ou 3). Est-ce que les résultats sont surprenants ?






